build:
  maxIssues: 0

complexity:
  TooManyFunctions:
    excludes:
      - "**/platform/**"
  LongParameterList:
    ignoreAnnotated:
      - Composable

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview

style:
  MaxLineLength:
    active: true
    maxLineLength: 140
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - Preview
