coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - "**/app/*.kt"
  - "**/*Screen.kt"
  - "**/*ScreenContent.kt"
  - "**/*DialogContent.kt"
  - "**/presentation/components/*.kt"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  hide_project_coverage: false
